# Generated by Django 3.1 on 2023-06-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0002_auto_20230620_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizado')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizado')),
                ('observation_date', models.DateField(verbose_name='Fecha')),
                ('place', models.CharField(max_length=150, verbose_name='Lugar')),
                ('distance', models.CharField(max_length=150, verbose_name='Distancia')),
                ('method', models.CharField(max_length=150, verbose_name='Método')),
                ('latitud', models.CharField(max_length=150, verbose_name='Latitud')),
                ('longitud', models.CharField(max_length=150, verbose_name='Longitud')),
                ('observation_type', models.CharField(max_length=150, verbose_name='Tipo')),
                ('indqty', models.CharField(max_length=150, verbose_name='Indqty')),
                ('life_stage', models.CharField(max_length=150, verbose_name='Etapa de vida')),
                ('activity', models.CharField(max_length=150, verbose_name='Actividad')),
                ('microhabitat', models.CharField(max_length=150, verbose_name='Microhabitat')),
                ('habitat', models.CharField(max_length=150, verbose_name='Habitat')),
                ('state', models.CharField(max_length=150, verbose_name='Estado')),
                ('url_photo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Url foto')),
                ('url_web', models.CharField(blank=True, max_length=150, null=True, verbose_name='Url web')),
                ('license', models.CharField(blank=True, max_length=150, null=True, verbose_name='Licencia')),
                ('sources', models.ManyToManyField(related_name='sources_observations', to='observations.Source', verbose_name='Fuentes')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specie_observation', to='species.specie', verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
            },
        ),
    ]
