# Generated by Django 3.1 on 2023-06-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='longitud',
            new_name='longitude',
        ),
    ]
