# Generated by Django 3.1 on 2023-06-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportFile',
        ),
    ]
