# Generated by Django 3.1 on 2023-06-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Familia', 'verbose_name_plural': 'Familias'},
        ),
    ]
