# Generated by Django 3.1 on 2023-10-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_auto_20230921_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='stage_life',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.DeleteModel(
            name='StageLife',
        ),
    ]
