# Generated by Django 3.1 on 2023-11-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_auto_20231018_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='phylum',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Còdigo'),
        ),
    ]
